name = "telegleam"
version = "1.0.0"

target = "javascript"

description = "A command line tool for doing stuff on Telegram with the Bot API"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jachin", repo = "telegleam" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
glint = ">= 1.2.1 and < 2.0.0"
simplifile = "~> 2.2"
filepath = ">= 1.1.2 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
flash = ">= 2.0.0 and < 3.0.0"
gtui = ">= 0.1.0 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
file_streams = ">= 1.5.0 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
multipart_form = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
